backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: "images/uploads"
collections:
  - name: "blog"
    label: "Blog"
    folder: "cms/_posts/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    description: >
      Add posts about recent activities, news, and stories related to your mission.
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Author",
          name: "author",
          widget: "relation",
          collection: "authors",
          display_fields: [display_name],
          search_fields: [display_name],
          value_field: "name",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
